INSERT INTO employee (employee_name, duty, manager_id)
VALUES ('John Doe', 'Manager', NULL),
       ('Jane Smith', 'Assistant', 1),
       ('Michael Johnson', 'Clerk', 2),
       ('Emily Davis', 'Assistant', 1),
       ('David Brown', 'Clerk', 2),
       ('Sarah Wilson', 'Clerk', 2),
       ('Jennifer Lee', 'Assistant', 1),
       ('Robert Taylor', 'Manager', NULL),
       ('Karen Anderson', 'Assistant', 8),
       ('Daniel Clark', 'Clerk', 9),
       ('Michelle Harris', 'Clerk', 9),
       ('Andrew Thompson', 'Assistant', 8),
       ('Jessica Martinez', 'Manager', NULL),
       ('Christopher Walker', 'Assistant', 13),
       ('Laura King', 'Clerk', 14),
       ('William Turner', 'Clerk', 14),
       ('Stephanie Scott', 'Assistant', 13),
       ('Jason Young', 'Manager', NULL),
       ('Melissa Rodriguez', 'Assistant', 17),
       ('Richard Hall', 'Clerk', 18);
